services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: fintor
      POSTGRES_USER: fintor
      POSTGRES_PASSWORD: fintor
    ports:
      - "5432:5432"
    volumes:
      - fintor_pgdata:/var/lib/postgresql/data

volumes:
  fintor_pgdata: